# These are supported funding model platforms
github: [Eliasar54]
patreon: ['https://patreon.com/Infinity_wa_hosting']
open_collective: # Replace with a single Open Collective username
ko_fi: ['https://ko-fi.com/infinitywa']
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: 
  - 'https://github.com/Eliasar54/ansi-BOT-MD'
  - 'https://whatsapp.com/channel/0029VadxAUkKLaHjPfS1vP36'
  - 'https://dash.infinitywa-host.com/register?ref=TSArjgj3'
  - 'https://dash.corinplus.com'
